package de.carsten.android.muzzic.persistence

import androidx.room.testing.MigrationTestHelper
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import de.carsten.android.muzzic.persistence.migrations.Migrations
import java.io.IOException
import org.junit.Assert.assertEquals
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class MigrationTest {
    private val testDbName = "migration-test"

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        MuzzicDatabase::class.java,
    )

    @Test
    @Throws(IOException::class)
    fun migrate1To2() {
        var db = helper.createDatabase(testDbName, 1)

        // Insert data into playlists table which should persist
        db.execSQL(
            "INSERT INTO playlists (id, name, isAutoGenerated, genre, createdAt, updatedAt) " +
                "VALUES ('p1', 'Test Playlist', 0, 'Rock', 123456789, 123456789)",
        )

        // play_history existed in v1
        db.execSQL("CREATE TABLE IF NOT EXISTS play_history (id TEXT PRIMARY KEY NOT NULL, songId TEXT NOT NULL, playedAt INTEGER NOT NULL)")
        db.execSQL("INSERT INTO play_history (id, songId, playedAt) VALUES ('h1', 's1', 987654321)")

        db.close()

        // Re-open the database with version 2 and provide all migrations
        db = helper.runMigrationsAndValidate(testDbName, 2, true, *Migrations.supply())

        // Validation 1: play_history should be gone
        val cursor = db.query("SELECT name FROM sqlite_master WHERE type='table' AND name='play_history'")
        assertEquals("Table play_history should have been dropped", 0, cursor.count)
        cursor.close()

        // Validation 2: playlists should still be there
        val playlistCursor = db.query("SELECT * FROM playlists WHERE id = 'p1'")
        assertEquals("Playlist data should have been preserved", 1, playlistCursor.count)
        playlistCursor.moveToFirst()
        assertEquals("Test Playlist", playlistCursor.getString(playlistCursor.getColumnIndex("name")))
        playlistCursor.close()
    }

    @Test
    @Throws(IOException::class)
    fun migrate2To3() {
        val testDbName = "migration-test-2to3"
        var db = helper.createDatabase(testDbName, 2)

        // Insert a song which the play_history table will reference
        db.execSQL(
            "INSERT INTO songs (id, title, artist, album, genre, playCount, lastPlayed) " +
                "VALUES ('s1', 'Song', 'Artist', 'Album', 'Rock', 3, 1000)",
        )

        db.close()

        // Re-open the database with version 3 and provide all migrations
        db = helper.runMigrationsAndValidate(testDbName, 3, true, *Migrations.supply())

        // Validation 1: play_history table should exist
        val tableCursor = db.query("SELECT name FROM sqlite_master WHERE type='table' AND name='play_history'")
        assertEquals("Table play_history should have been created", 1, tableCursor.count)
        tableCursor.close()

        // Validation 2: index on songId should exist
        val indexCursor = db.query("SELECT name FROM sqlite_master WHERE type='index' AND name='index_play_history_songId'")
        assertEquals("Index index_play_history_songId should have been created", 1, indexCursor.count)
        indexCursor.close()

        // Validation 3: inserted row should be insertable into play_history
        db.execSQL(
            "INSERT INTO play_history (id, songId, playedAt) VALUES ('h1', 's1', 2000)",
        )
        val historyCursor = db.query("SELECT * FROM play_history WHERE id = 'h1'")
        assertEquals("Play history row should be present", 1, historyCursor.count)
        historyCursor.close()
    }
}
