package de.carsten.android.muzzic.persistence

import androidx.room.testing.MigrationTestHelper
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import de.carsten.android.muzzic.persistence.migrations.Migrations
import org.junit.Assert.assertEquals
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import java.io.IOException

@RunWith(AndroidJUnit4::class)
class MigrationTest {
    private val testDbName = "migration-test"

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        MuzzicDatabase::class.java,
    )

    @Test
    @Throws(IOException::class)
    fun migrate1To2() {
        var db = helper.createDatabase(testDbName, 1)

        // Insert data into playlists table which should persist
        db.execSQL(
            "INSERT INTO playlists (id, name, isAutoGenerated, genre, createdAt, updatedAt) " +
                "VALUES ('p1', 'Test Playlist', 0, 'Rock', 123456789, 123456789)"
        )

        // play_history existed in v1
        db.execSQL("CREATE TABLE IF NOT EXISTS play_history (id TEXT PRIMARY KEY NOT NULL, songId TEXT NOT NULL, playedAt INTEGER NOT NULL)")
        db.execSQL("INSERT INTO play_history (id, songId, playedAt) VALUES ('h1', 's1', 987654321)")

        db.close()

        // Re-open the database with version 2 and provide all migrations
        db = helper.runMigrationsAndValidate(testDbName, 2, true, *Migrations.supply())

        // Validation 1: play_history should be gone
        val cursor = db.query("SELECT name FROM sqlite_master WHERE type='table' AND name='play_history'")
        assertEquals("Table play_history should have been dropped", 0, cursor.count)
        cursor.close()

        // Validation 2: playlists should still be there
        val playlistCursor = db.query("SELECT * FROM playlists WHERE id = 'p1'")
        assertEquals("Playlist data should have been preserved", 1, playlistCursor.count)
        playlistCursor.moveToFirst()
        assertEquals("Test Playlist", playlistCursor.getString(playlistCursor.getColumnIndex("name")))
        playlistCursor.close()
    }
}
