package de.carsten.android.muzzic.persistence.entity

import androidx.room.Entity

@Entity(tableName = "playlists")
data class Playlist(
    val name: String,
    val isAutoGenerated: Boolean = false,
    val genre: String? = null,
) : AbstractEntity()
