package de.carsten.android.muzzic.persistence.entity

import androidx.media3.common.MediaItem
import androidx.media3.common.MediaMetadata
import androidx.room.Entity
import de.carsten.android.muzzic.model.MediaKeys

@Entity(tableName = "playlists")
data class Playlist(
    val name: String,
    val isAutoGenerated: Boolean = false,
    val genre: String? = null,
) : AbstractEntity()

fun Playlist.toMediaItem(): MediaItem {
    return MediaItem.Builder()
        .setMediaId("${MediaKeys.PLAYLIST_PREFIX}$name")
        .setMediaMetadata(
            MediaMetadata.Builder()
                .setTitle(name)
                .setExtras(android.os.Bundle().apply {
                    putBoolean(MediaKeys.IS_AUTO_GENERATED, isAutoGenerated)
                    putString(MediaKeys.GENRE, genre ?: UNKNOWN)
                })
                .setIsBrowsable(true)
                .setIsPlayable(false)
                .build()
        )
        .build()
}
