apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
    tier: backend
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: backend
  strategy: { }
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
    spec:
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - image: postgres:16
          imagePullPolicy: IfNotPresent
          name: postgres
          envFrom:
            - configMapRef:
                name: postgres
            - secretRef:
                name: postgres
          volumeMounts:
            - name: postgresdata
              mountPath: /var/lib/postgresql/data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
    tier: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
  strategy: { }
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
        - image: de.carsten.spring-react.backend:1.0.0-SNAPSHOT
          imagePullPolicy: Never
          name: backend
          resources: { }
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s-minikube"
            - name: SPRINGDOC_SWAGGER_UI_URL
              value: "/backend/openapi"
            - name: SWAGGER_SERVER_URL
              value: "http://localhost/backend"
            - name: SWAGGER_SERVER_DESC
              value: "K8s backend API"
            - name: SPRING_SECURITY_KEYCLOAK_HOSTNAME
              value: "http://keycloak.localhost.nip.io"
            - name: SPRING_BACKEND_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: client_secret
