apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: postgres
    tier: backend
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  labels:
    app: backend
    tier: backend
type: Opaque
data:
  SPRING_BACKEND_CLIENT_SECRET: a3VPbzUyV3FSdE94eDFUN3o5N1hycEh1NGdzSFNVd3g=
