apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: postgres
spec:
  ports:
    - name: 5432-5432
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: backend
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
    - name: 8081-8080
      port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: backend
                port:
                  number: 8081
            pathType: Prefix
            path: /
