apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-svc
    tier: backend
  name: postgres
spec:
  ports:
    - name: 5432-5432
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
    tier: backend
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-svc
    tier: backend
  name: backend
spec:
  ports:
    - name: 8081-8080
      port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend
    tier: backend
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /backend(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 8081
