package de.carsten.android.muzzic.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import de.carsten.android.muzzic.persistence.repo.GenreRepository
import de.carsten.android.muzzic.persistence.repo.MusicRepository
import de.carsten.android.muzzic.persistence.repo.PlaylistRepository
import de.carsten.android.muzzic.ui.state.StatisticsUiState
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

class StatisticsViewModel(private val repository: MusicRepository, private val genreRepository: GenreRepository, private val playlistRepository: PlaylistRepository) :
    ViewModel() {
    private val _uiState = MutableStateFlow(StatisticsUiState())
    val uiState: StateFlow<StatisticsUiState> = _uiState.asStateFlow()

    init {
        // Initial load
        loadStats()
    }

    fun loadStats() {
        viewModelScope.launch {
            val librarySummary = repository.getLibrarySummary()
            val genreDurations = genreRepository.getGenreInformation().first()
            val playlistDurations = playlistRepository.getPlaylistInformation().first()
                .filter { !it.playlistIsAutoGenerated }

            _uiState.update {
                it.copy(
                    monthlyStats = repository.getMonthlyStats(),
                    genreStats = repository.getGenreStats(),
                    topSongs = repository.getTopSongs(),
                    monthStats = repository.getMonthStats(),
                    monthGenreStats = repository.getMonthGenreStats(),
                    topMonthSongs = repository.getTopMonthSongs(),
                    librarySummary = librarySummary,
                    genreDurations = genreDurations,
                    playlistDurations = playlistDurations,
                )
            }
        }
    }
}
