<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.bmw.bigdata.tracenet</groupId>
    <artifactId>feger-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <asm.version>6.0</asm.version>
        <glassfish-deployment-client.version>4.1.2</glassfish-deployment-client.version>
        <java.version>1.7</java.version>
        <javaee.version>7.0</javaee.version>
        <junit.version>4.12</junit.version>
        <maven-assembly-plugin.version>3.1.0</maven-assembly-plugin.version>
        <maven-cargo-plugin.version>1.6.5</maven-cargo-plugin.version>
        <maven-compiler-plugin.version>3.7.0</maven-compiler-plugin.version>
        <maven-resources-plugin.version>3.0.2</maven-resources-plugin.version>
        <maven-surefire-plugin.version>2.20.1</maven-surefire-plugin.version>
        <maven-war-plugin.version>3.2.0</maven-war-plugin.version>
        <payara.adminPort>4848</payara.adminPort>
        <payara.hostname>localhost</payara.hostname>
        <payara.password></payara.password>
        <payara.username>admin</payara.username>
    </properties>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>${javaee.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <modules>
        <module>database</module>
        <module>bigdata</module>
        <module>service</module>
    </modules>

    <profiles>
        <profile>
            <id>payara</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.cargo</groupId>
                        <artifactId>cargo-maven2-plugin</artifactId>
                        <version>${maven-cargo-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>install-in-payara</id>
                                <phase>install</phase>
                                <goals>
                                    <goal>redeploy</goal>
                                </goals>
                                <configuration>
                                    <container>
                                        <containerId>glassfish4x</containerId>
                                        <type>remote</type>
                                    </container>
                                    <configuration>
                                        <type>runtime</type>
                                        <properties>
                                            <cargo.remote.username>${payara.username}</cargo.remote.username>
                                            <cargo.remote.password>${payara.password}</cargo.remote.password>
                                            <cargo.glassfish.admin.port>${payara.adminPort}</cargo.glassfish.admin.port>
                                            <cargo.hostname>${payara.hostname}</cargo.hostname>
                                        </properties>
                                    </configuration>
                                </configuration>
                            </execution>
                        </executions>
                        <dependencies>
                            <dependency>
                                <groupId>org.glassfish.main.deployment</groupId>
                                <artifactId>deployment-client</artifactId>
                                <version>${glassfish-deployment-client.version}</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
