package de.carsten.android.muzzic.persistence.entity.aggregation

import de.carsten.android.muzzic.model.AlbumArt

data class PlaylistAggregation(
    val playlistId: String,
    val playlistName: String,
    val playlistIsAutoGenerated: Boolean,
    val playlistGenre: String?,
    val artistCount: Int,
    val albumCount: Int,
    val songCount: Int,
    val playlistDuration: Long,
    override val lastAlbumArt: String? = null,
    val allAlbumArts: String? = null,
) : AlbumArt
