package de.carsten.android.muzzic.scanning

import android.content.Context
import androidx.test.core.app.ApplicationProvider
import de.carsten.android.muzzic.TestConfig
import de.carsten.android.muzzic.persistence.dao.GenreDao
import de.carsten.android.muzzic.persistence.dao.PlaylistDao
import de.carsten.android.muzzic.persistence.dao.SongDao
import de.carsten.android.muzzic.persistence.entity.Playlist
import de.carsten.android.muzzic.persistence.entity.PlaylistSong
import de.carsten.android.muzzic.persistence.entity.Song
import de.carsten.android.muzzic.persistence.entity.aggregation.GenrePlayCount
import de.carsten.android.muzzic.persistence.repo.AppSettingsRepository
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import io.mockk.slot
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.assertj.core.api.Assertions.assertThat
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Unit tests for automatic playlist genre grouping in [MusicFileScanner].
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [TestConfig.SDK])
class MusicFileScannerAutomaticPlaylistsTest {

    private val context: Context = ApplicationProvider.getApplicationContext()
    private val songDao: SongDao = mockk()
    private val genreDao: GenreDao = mockk()
    private val playlistDao: PlaylistDao = mockk()
    private val appSettingsRepository: AppSettingsRepository = mockk()

    private lateinit var scanner: MusicFileScanner

    @Before
    fun setup() {
        scanner = MusicFileScanner(context, songDao, genreDao, playlistDao, appSettingsRepository)
    }

    @Test
    fun `death core variants are merged into one canonical playlist`() = runTest {
        val topDeathCore = Song(title = "A", artist = "X", album = "M", genre = "Death Core", rating = 5, playCount = 1)
        val topDeathcore = Song(title = "B", artist = "Y", album = "M", genre = "Deathcore", rating = 4, playCount = 9)
        val topDeathHyphen = Song(title = "C", artist = "Z", album = "M", genre = "Death-Core", rating = 1, playCount = 1)
        coEvery { genreDao.getGenreCounts() } returns listOf(
            GenrePlayCount("Death Core", 2),
            GenrePlayCount("Deathcore", 4),
            GenrePlayCount("Death-Core", 1),
        )
        coEvery { genreDao.getTopSongsByGenre("Death Core", 100) } returns listOf(topDeathCore)
        coEvery { genreDao.getTopSongsByGenre("Deathcore", 100) } returns listOf(topDeathcore)
        coEvery { genreDao.getTopSongsByGenre("Death-Core", 100) } returns listOf(topDeathHyphen)
        every { playlistDao.getAllPlaylists() } returns flowOf(emptyList())
        coEvery { playlistDao.insertPlaylist(any()) } returns 1L
        coEvery { playlistDao.clearPlaylist(any()) } returns Unit
        coEvery { playlistDao.insertPlaylistSongs(any()) } returns Unit

        scanner.updateAutomaticPlaylists()

        val playlistSlot = slot<Playlist>()
        coVerify(exactly = 1) { playlistDao.insertPlaylist(capture(playlistSlot)) }
        assertThat(playlistSlot.captured.name).isEqualTo("Death Core - Top 100")
        assertThat(playlistSlot.captured.genre).isEqualTo("Death Core")
        assertThat(playlistSlot.captured.isAutoGenerated).isTrue()

        val songsSlot = slot<List<PlaylistSong>>()
        coVerify(exactly = 1) { playlistDao.insertPlaylistSongs(capture(songsSlot)) }
        val capturedSongs = songsSlot.captured
        assertThat(capturedSongs).hasSize(3)
        assertThat(capturedSongs.map { it.position }).containsExactly(0, 1, 2)
        assertThat(capturedSongs.map { it.songId }).containsExactly(
            topDeathCore.id,
            topDeathcore.id,
            topDeathHyphen.id,
        )
    }

    @Test
    fun `stale variant playlists are removed`() = runTest {
        val stale = Playlist(name = "Deathcore - Top 100", isAutoGenerated = true, genre = "Deathcore")
        val userPlaylist = Playlist(name = "Deathcore - Top 100", isAutoGenerated = false, genre = null)
        coEvery { genreDao.getGenreCounts() } returns listOf(GenrePlayCount("Death Core", 2))
        coEvery { genreDao.getTopSongsByGenre("Death Core", 100) } returns emptyList()
        every { playlistDao.getAllPlaylists() } returns flowOf(listOf(stale, userPlaylist))
        coEvery { playlistDao.clearPlaylist(any()) } returns Unit
        coEvery { playlistDao.deletePlaylist(any()) } returns Unit
        coEvery { playlistDao.insertPlaylist(any()) } returns 1L
        coEvery { playlistDao.insertPlaylistSongs(any()) } returns Unit

        scanner.updateAutomaticPlaylists()

        coVerify(exactly = 1) { playlistDao.deletePlaylist(stale.id) }
        coVerify(exactly = 0) { playlistDao.deletePlaylist(userPlaylist.id) }
    }
}
