package de.carsten.android.muzzic.ui.screens.cards

import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Album
import androidx.compose.material.icons.filled.MusicNote
import androidx.compose.material.icons.filled.Person
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import de.carsten.android.muzzic.ui.MAINTITLE_FONTSIZE
import de.carsten.android.muzzic.ui.PREVIEW_DARK_MODE
import de.carsten.android.muzzic.ui.model.CoverSource
import de.carsten.android.muzzic.ui.model.PlaylistDto

@Composable
fun PlaylistCard(playlist: PlaylistDto, onClick: () -> Unit = {}) {
    val palette by rememberPaletteState(playlist.lastAlbumArt)
    val backgroundColor = Color(palette?.getDominantColor(MaterialTheme.colorScheme.primaryContainer.hashCode()) ?: MaterialTheme.colorScheme.primaryContainer.hashCode())
    val contentColor = Color(palette?.getDominantSwatch()?.bodyTextColor ?: MaterialTheme.colorScheme.onPrimaryContainer.hashCode())

    MuzzicCard(
        header = {
            AlbumCoverCollage(
                covers =
                if (playlist.lastAlbumArt == null) {
                    emptyList()
                } else {
                    listOf(CoverSource.FromPath(playlist.lastAlbumArt))
                },
                modifier =
                Modifier
                    .fillMaxWidth()
                    .aspectRatio(1.2f),
                useCard = false,
            )
        },
        backgroundColor = backgroundColor,
        contentColor = contentColor,
        onClick = onClick,
    ) {
        Text(
            text = playlist.playlistName,
            color = it,
            fontSize = MAINTITLE_FONTSIZE,
            fontWeight = FontWeight.SemiBold,
            textAlign = TextAlign.Center,
            maxLines = 1,
            overflow = TextOverflow.Ellipsis,
        )

        Spacer(modifier = Modifier.height(4.dp))

        SubtitleInformation(
            listOf(
                Pair(Icons.Default.Person, "${playlist.artistCount} Artists"),
                Pair(Icons.Default.Album, "${playlist.albumCount} Albums"),
                Pair(Icons.Default.MusicNote, "${playlist.songCount} Songs"),
            ),
            fontColor = it.copy(alpha = 0.8f),
        )
    }
}

@Composable
@Preview
@Preview(uiMode = PREVIEW_DARK_MODE, name = "PlaylistCardPreview_Dark")
fun PlaylistCardPreview() {
    PlaylistCard(
        PlaylistDto(
            playlistId = "1",
            playlistName = "Rock Anthems",
            playlistIsAutoGenerated = false,
            playlistGenre = "Rock",
            artistCount = 25,
            albumCount = 40,
            songCount = 100,
            playlistDuration = 5 * 60 * 60 * 1000L,
        ),
    )
}
