package de.carsten.android.muzzic.persistence.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import de.carsten.android.muzzic.AppConfig
import de.carsten.android.muzzic.persistence.entity.Playlist
import de.carsten.android.muzzic.persistence.entity.PlaylistSong
import de.carsten.android.muzzic.persistence.entity.Song
import de.carsten.android.muzzic.persistence.entity.aggregation.PlaylistAggregation
import kotlinx.coroutines.flow.Flow

@Dao
interface PlaylistDao {
    @Query("SELECT * FROM playlists ORDER BY name ASC")
    fun getAllPlaylists(): Flow<List<Playlist>>

    @Query("SELECT * FROM playlists WHERE name LIKE '%' || :query || '%' ORDER BY name ASC")
    suspend fun searchPlaylists(query: String): List<Playlist>

    @Query(
        "SELECT s.* FROM songs s INNER JOIN playlist_songs ps ON s.id = ps.songId WHERE ps.playlistId = :playlistId ORDER BY ps.position",
    )
    suspend fun getSongsInPlaylist(playlistId: String): List<Song>

    @Query(
        value = """
        SELECT s.*
        FROM songs s
        INNER JOIN playlist_songs ps ON ps.songId = s.id
        INNER JOIN playlists p ON p.id = ps.playlistId
        WHERE p.name = :playlistName
        """,
    )
    suspend fun getSongsByPlaylist(playlistName: String): List<Song>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertPlaylist(playlist: Playlist): Long

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertPlaylistSong(playlistSong: PlaylistSong)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertPlaylistSongs(playlistSongs: List<PlaylistSong>)

    @Query("DELETE FROM playlist_songs WHERE playlistId = :playlistId")
    suspend fun clearPlaylist(playlistId: String)

    @Query("DELETE FROM playlists WHERE id = :playlistId")
    suspend fun deletePlaylist(playlistId: String)

    @Query("DELETE FROM playlists")
    suspend fun deleteAllPlaylists()

    @Query(
        """
        SELECT
            p.id AS playlistId,
            p.name AS playlistName,
            p.isAutoGenerated AS playlistIsAutoGenerated,
            p.genre as playlistGenre,
            COUNT(DISTINCT s.artist) AS artistCount,
            COUNT(DISTINCT s.album) AS albumCount,
            COUNT(s.id) AS songCount,
            COALESCE(SUM(s.duration), 0) as playlistDuration,
            (SELECT s2.albumArt
             FROM songs s2
             JOIN playlist_songs ps2 ON s2.id = ps2.songId
             WHERE ps2.playlistId = p.id
             ORDER BY s2.createdAt DESC
             LIMIT 1) as lastAlbumArt,
            (SELECT GROUP_CONCAT(albumArt)
             FROM (SELECT MIN(s3.albumArt) as albumArt
                   FROM songs s3
                   JOIN playlist_songs ps3 ON s3.id = ps3.songId
                   WHERE ps3.playlistId = p.id AND s3.albumArt IS NOT NULL
                   GROUP BY s3.artist, s3.album
                   ORDER BY MAX(s3.createdAt) DESC
                   LIMIT ${AppConfig.Persistence.ALBUM_ART_LIMIT})) as allAlbumArts
        FROM playlists p
        LEFT JOIN playlist_songs ps ON ps.playlistId = p.id
        LEFT JOIN songs s ON s.id = ps.songId
        GROUP BY p.id, p.name, p.isAutoGenerated, p.genre
        ORDER BY p.name ASC, playlistDuration ASC
        """,
    )
    fun getPlaylistAggregation(): Flow<List<PlaylistAggregation>>
}
