app:
  database:
    name: tutorialsdb
    schema: tutorials
    port: 5432
    username: postgres
    password: postgres

management:
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: spring-react

  profiles:
    default: dev
    active: dev

  flyway:
    default-schema: ${app.database.schema}
    validate-on-migrate: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${app.database.port}/${app.database.name}
    username: ${app.database.username}
    password: ${app.database.password}

  r2dbc:
    url: r2dbc:postgresql://localhost:${app.database.port}/${app.database.name}
    username: ${app.database.username}
    password: ${app.database.password}

  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
      lifecycle-management: start_only

  devtools:
    restart:
      poll-interval: 4s
      quiet-period: 2s
    livereload:
      enabled: true

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
  api-docs:
    path: /openapi

logging:
  level:
    org.jooq.Constants: WARN
