app:
  database:
    host: localhost
    name: tutorialsdb
    schema: tutorials
    port: 5432
    username: postgres
    password: postgres

  frontend:
    index-html-path: "/index.html"

  web:
    cors:
      mappings: "/api/**,/backend/**,/backend/api/**"
      patterns: "*"

  swagger:
    title: "Tutorials API"
    version: 1.0.0
    description: "A small demo API based on Spring-Boot"
    server:
      url: ${SWAGGER_SERVER_URL:http://localhost:8080}
      description: ${SWAGGER_SERVER_DESC:Local backend api}

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: spring-react

  flyway:
    default-schema: ${app.database.schema}
    validate-on-migrate: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.name}
    username: ${app.database.username}
    password: ${app.database.password}

  r2dbc:
    url: r2dbc:postgresql://${app.database.host}:${app.database.port}/${app.database.name}
    username: ${app.database.username}
    password: ${app.database.password}

  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
      lifecycle-management: start_only

  devtools:
    restart:
      poll-interval: 4s
      quiet-period: 2s
    livereload:
      enabled: true


springdoc:
  show-actuator: true
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    url: ${SPRINGDOC_SWAGGER_UI_URL:/openapi}
    disable-swagger-default-url: true
    config-url: ${springdoc.swagger-ui.url}/swagger-config

logging:
  level:
    org.jooq.Constants: WARN
