app:
  database:
    host: localhost
    name: tutorialsdb
    schema: tutorials
    port: 5432
    username: postgres
    password: postgres

  frontend:
    index-html-path: "/index.html"

  web:
    security:
      keycloak-hostname: "${SPRING_SECURITY_KEYCLOAK_HOSTNAME:http://localhost:8090}"
      issuer-uri: "${app.web.security.keycloak-hostname}/realms/tutorials_realm"
    cors:
      mappings: "/api/**,/backend/**,/backend/api/**"
      patterns: "*"

  swagger:
    title: "Tutorials API"
    version: 1.0.0
    description: "A small demo API based on Spring-Boot"
    server:
      url: ${SWAGGER_SERVER_URL:http://localhost:8080}
      description: ${SWAGGER_SERVER_DESC:Local backend api}

  users:
    tutorialUser: "tutorial_user"

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: spring-react

  flyway:
    default-schema: ${app.database.schema}
    validate-on-migrate: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.name}
    username: ${app.database.username}
    password: ${app.database.password}

  r2dbc:
    url: r2dbc:postgresql://${app.database.host}:${app.database.port}/${app.database.name}
    username: ${app.database.username}
    password: ${app.database.password}

  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
      lifecycle-management: start_only

  devtools:
    restart:
      poll-interval: 4s
      quiet-period: 2s
    livereload:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: backend_client
            client-secret: ${SPRING_BACKEND_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${app.web.security.issuer-uri}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${app.web.security.issuer-uri}


springdoc:
  show-actuator: true
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    url: ${SPRINGDOC_SWAGGER_UI_URL:/openapi}
    config-url: ${springdoc.swagger-ui.url}/swagger-config

logging:
  level:
    org.jooq.Constants: WARN
