package de.carsten.android.muzzic.ui.screens.grids

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.pager.HorizontalPager
import androidx.compose.foundation.pager.rememberPagerState
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.PrimaryTabRow
import androidx.compose.material3.Surface
import androidx.compose.material3.Tab
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import de.carsten.android.muzzic.R
import de.carsten.android.muzzic.ui.GLASS_CONTAINER_ALPHA
import de.carsten.android.muzzic.ui.GRID_HORIZONTAL_PADDING
import de.carsten.android.muzzic.ui.GRID_SPACING
import de.carsten.android.muzzic.ui.PREVIEW_DARK_MODE
import de.carsten.android.muzzic.ui.model.PlaylistDto
import de.carsten.android.muzzic.ui.screens.cards.PlaylistCard
import de.carsten.android.muzzic.ui.theme.AppTheme
import kotlinx.coroutines.launch

@Composable
fun PlaylistGrid(playlists: List<PlaylistDto>, modifier: Modifier = Modifier, initialPage: Int = 0, onPlaylistClick: (PlaylistDto) -> Unit = {}) {
    val autoPlaylists = remember(playlists) {
        playlists.filter { it.playlistIsAutoGenerated }
    }
    val myPlaylists = remember(playlists) {
        playlists.filter { !it.playlistIsAutoGenerated }
    }

    val pagerState = rememberPagerState(
        initialPage = initialPage,
        pageCount = { 2 },
    )
    val coroutineScope = rememberCoroutineScope()

    val tabs = listOf(
        stringResource(R.string.auto_playlists),
        stringResource(R.string.my_playlists),
    )

    Column(modifier = modifier.fillMaxSize()) {
        PrimaryTabRow(
            selectedTabIndex = pagerState.currentPage,
            modifier = Modifier.fillMaxWidth(),
            containerColor = MaterialTheme.colorScheme.surface.copy(alpha = 0f),
        ) {
            tabs.forEachIndexed { index, title ->
                Tab(
                    selected = pagerState.currentPage == index,
                    onClick = {
                        coroutineScope.launch {
                            pagerState.animateScrollToPage(index)
                        }
                    },
                    text = {
                        Text(
                            text = title,
                            fontWeight = if (pagerState.currentPage == index) FontWeight.Bold else FontWeight.Normal,
                        )
                    },
                )
            }
        }

        HorizontalPager(
            state = pagerState,
            modifier = Modifier.fillMaxSize(),
            verticalAlignment = Alignment.Top,
        ) { pageIndex ->
            InternalPlaylistGrid(
                playlists = if (pageIndex == 0) autoPlaylists else myPlaylists,
                onPlaylistClick = onPlaylistClick,
            )
        }
    }
}

@Composable
private fun InternalPlaylistGrid(playlists: List<PlaylistDto>, onPlaylistClick: (PlaylistDto) -> Unit) {
    LazyVerticalGrid(
        columns = GridCells.Fixed(2),
        modifier = Modifier.fillMaxSize(),
        contentPadding = PaddingValues(
            horizontal = GRID_HORIZONTAL_PADDING,
            vertical = 12.dp,
        ),
        verticalArrangement = Arrangement.spacedBy(GRID_SPACING),
        horizontalArrangement = Arrangement.spacedBy(GRID_SPACING),
    ) {
        items(
            items = playlists,
            key = { it.lazyKey() },
            contentType = { it.lazyContentType() },
        ) { playlist ->
            PlaylistCard(
                playlist = playlist,
                onClick = {
                    onPlaylistClick(playlist)
                },
            )
        }
    }
}

private val previewPlaylists = listOf(
    PlaylistDto(
        playlistId = "1",
        playlistName = "TopAlternative",
        playlistIsAutoGenerated = true,
        playlistGenre = "Alternative",
        artistCount = 25,
        albumCount = 40,
        songCount = 100,
        playlistDuration = 5 * 60 * 60 * 1000L,
    ),
    PlaylistDto(
        playlistId = "2",
        playlistName = "TopBlackMetal",
        playlistIsAutoGenerated = true,
        playlistGenre = "Black Metal",
        artistCount = 25,
        albumCount = 40,
        songCount = 100,
        playlistDuration = 5 * 60 * 60 * 1000L,
    ),
    PlaylistDto(
        playlistId = "3",
        playlistName = "Jogging",
        playlistIsAutoGenerated = false,
        playlistGenre = "Mixed",
        artistCount = 25,
        albumCount = 40,
        songCount = 100,
        playlistDuration = 5 * 60 * 60 * 1000L,
    ),
)

@Composable
@Preview(showBackground = true, name = "Auto Playlists")
@Preview(uiMode = PREVIEW_DARK_MODE, name = "Auto Playlists Dark", showBackground = true)
fun PlaylistGridAutoPreview() {
    AppTheme {
        Surface(
            modifier = Modifier.fillMaxSize(),
            color = MaterialTheme.colorScheme.surface.copy(alpha = GLASS_CONTAINER_ALPHA),
        ) {
            PlaylistGrid(previewPlaylists)
        }
    }
}

@Composable
@Preview(showBackground = true, name = "My Playlists")
@Preview(uiMode = PREVIEW_DARK_MODE, name = "My Playlists Dark", showBackground = true)
fun PlaylistGridMyPreview() {
    AppTheme {
        Surface(
            modifier = Modifier.fillMaxSize(),
            color = MaterialTheme.colorScheme.surface.copy(alpha = GLASS_CONTAINER_ALPHA),
        ) {
            PlaylistGrid(
                playlists = previewPlaylists,
                initialPage = 1,
            )
        }
    }
}
