package de.carsten.android.muzzic.ui.screens.grids

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import de.carsten.android.muzzic.R
import de.carsten.android.muzzic.ui.model.PlaylistDto
import de.carsten.android.muzzic.ui.screens.cards.PlaylistCard
import de.carsten.android.muzzic.ui.theme.CustomColors

@Composable
fun PlaylistGrid(playlists: List<PlaylistDto>, modifier: Modifier = Modifier, onPlaylistClick: (PlaylistDto) -> Unit = {}) {
    LazyColumn(
        modifier = modifier.padding(horizontal = 16.dp),
    ) {
        item {
            Text(
                text = stringResource(R.string.auto_playlists),
                color = CustomColors.autoPlaylists,
                fontSize = 12.sp,
                fontWeight = FontWeight.SemiBold,
                modifier = Modifier.padding(bottom = 12.dp),
            )
        }

        item {
            val autoPlaylists =
                remember(playlists) {
                    playlists.filter { it.playlistIsAutoGenerated }
                }
            LazyVerticalGrid(
                columns = GridCells.Fixed(2),
                modifier = Modifier.heightIn(100.dp, 400.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp),
                horizontalArrangement = Arrangement.spacedBy(16.dp),
            ) {
                items(
                    items = autoPlaylists.sorted(),
                    key = { playlist -> "${playlist.playlistName}_${playlist.playlistGenre}" },
                    contentType = { "Playlist" },
                ) { playlist ->
                    PlaylistCard(
                        playlist = playlist,
                        onClick = {
                            onPlaylistClick(playlist)
                        },
                    )
                }
            }
        }

        item {
            Spacer(modifier = Modifier.height(24.dp))
        }

        item {
            Text(
                text = stringResource(R.string.my_playlists),
                color = CustomColors.myPlaylists,
                fontSize = 12.sp,
                fontWeight = FontWeight.SemiBold,
                modifier = Modifier.padding(bottom = 12.dp),
            )
        }

        item {
            val myPlaylists =
                remember(playlists) {
                    playlists.filter { !it.playlistIsAutoGenerated }
                }
            LazyVerticalGrid(
                columns = GridCells.Fixed(2),
                modifier = Modifier.heightIn(100.dp, 400.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp),
                horizontalArrangement = Arrangement.spacedBy(16.dp),
            ) {
                items(
                    items = myPlaylists.sorted(),
                    key = { playlist -> "${playlist.playlistName}_${playlist.playlistGenre}" },
                    contentType = { "Playlist" },
                ) { playlist ->
                    PlaylistCard(
                        playlist = playlist,
                        onClick = {
                            onPlaylistClick(playlist)
                        },
                    )
                }
            }
        }
    }
}

@Composable
@Preview
fun PlaylistGridPreview() {
    PlaylistGrid(
        listOf(
            PlaylistDto(
                playlistId = "1",
                playlistName = "TopAlternative",
                playlistIsAutoGenerated = true,
                playlistGenre = "Alternative",
                artistCount = 25,
                albumCount = 40,
                songCount = 100,
                playlistDuration = 5 * 60 * 60 * 1000L,
            ),
            PlaylistDto(
                playlistId = "2",
                playlistName = "TopBlackMetal",
                playlistIsAutoGenerated = true,
                playlistGenre = "Black Metal",
                artistCount = 25,
                albumCount = 40,
                songCount = 100,
                playlistDuration = 5 * 60 * 60 * 1000L,
            ),
            PlaylistDto(
                playlistId = "3",
                playlistName = "Jogging",
                playlistIsAutoGenerated = false,
                playlistGenre = "Mixed",
                artistCount = 25,
                albumCount = 40,
                songCount = 100,
                playlistDuration = 5 * 60 * 60 * 1000L,
            ),
        ),
    )
}
