package de.carsten.android.muzzic.id3.model.frame

/**
 * All frame identifiers declared by ID3v2.3.0 and ID3v2.4.0.
 *
 * Each constant maps to exactly one typed frame class. Identifiers
 * marked as deprecated only appear in v2.3 tags; identifiers marked as
 * new only appear in v2.4 tags.
 */
object FrameIds {
    // 4.1 Unique file identifier
    const val UFID = "UFID"

    // 4.2 Text information frames (v2.4 set, shared unless noted)
    const val TALB = "TALB"
    const val TBPM = "TBPM"
    const val TCOM = "TCOM"
    const val TCON = "TCON"
    const val TCOP = "TCOP"
    const val TDEN = "TDEN"
    const val TDLY = "TDLY"
    const val TDOR = "TDOR"
    const val TDRC = "TDRC"
    const val TDRL = "TDRL"
    const val TDTG = "TDTG"
    const val TENC = "TENC"
    const val TEXT = "TEXT"
    const val TFLT = "TFLT"
    const val TIPL = "TIPL"
    const val TIT1 = "TIT1"
    const val TIT2 = "TIT2"
    const val TIT3 = "TIT3"
    const val TKEY = "TKEY"
    const val TLAN = "TLAN"
    const val TLEN = "TLEN"
    const val TMCL = "TMCL"
    const val TMED = "TMED"
    const val TMOO = "TMOO"
    const val TOAL = "TOAL"
    const val TOFN = "TOFN"
    const val TOLY = "TOLY"
    const val TOPE = "TOPE"
    const val TOWN = "TOWN"
    const val TPE1 = "TPE1"
    const val TPE2 = "TPE2"
    const val TPE3 = "TPE3"
    const val TPE4 = "TPE4"
    const val TPOS = "TPOS"
    const val TPRO = "TPRO"
    const val TPUB = "TPUB"
    const val TRCK = "TRCK"
    const val TRSN = "TRSN"
    const val TRSO = "TRSO"
    const val TSOA = "TSOA"
    const val TSOP = "TSOP"
    const val TSOT = "TSOT"
    const val TSRC = "TSRC"
    const val TSSE = "TSSE"
    const val TSST = "TSST"
    const val TXXX = "TXXX"

    // 4.3 URL link frames
    const val WCOM = "WCOM"
    const val WCOP = "WCOP"
    const val WOAF = "WOAF"
    const val WOAR = "WOAR"
    const val WOAS = "WOAS"
    const val WORS = "WORS"
    const val WPAY = "WPAY"
    const val WPUB = "WPUB"
    const val WXXX = "WXXX"

    // 4.4 - 4.30 special frames
    const val MCDI = "MCDI"
    const val ETCO = "ETCO"
    const val MLLT = "MLLT"
    const val SYTC = "SYTC"
    const val USLT = "USLT"
    const val SYLT = "SYLT"
    const val COMM = "COMM"
    const val RVA2 = "RVA2"
    const val EQU2 = "EQU2"
    const val RVRB = "RVRB"
    const val APIC = "APIC"
    const val GEOB = "GEOB"
    const val PCNT = "PCNT"
    const val POPM = "POPM"
    const val RBUF = "RBUF"
    const val AENC = "AENC"
    const val LINK = "LINK"
    const val POSS = "POSS"
    const val USER = "USER"
    const val OWNE = "OWNE"
    const val COMR = "COMR"
    const val ENCR = "ENCR"
    const val GRID = "GRID"
    const val PRIV = "PRIV"
    const val SIGN = "SIGN"
    const val SEEK = "SEEK"
    const val ASPI = "ASPI"

    // Deprecated v2.3-only frames
    const val EQUA = "EQUA"
    const val RVAD = "RVAD"
    const val IPLS = "IPLS"
    const val TDAT = "TDAT"
    const val TIME = "TIME"
    const val TORY = "TORY"
    const val TRDA = "TRDA"
    const val TSIZ = "TSIZ"
    const val TYER = "TYER"
}
