package de.carsten.android.muzzic.ui.model

import android.os.Bundle
import androidx.compose.runtime.Immutable
import androidx.core.net.toUri
import androidx.media3.common.MediaItem
import androidx.media3.common.MediaMetadata
import de.carsten.android.muzzic.EMPTY
import de.carsten.android.muzzic.UNKNOWN
import de.carsten.android.muzzic.model.AlbumArt
import de.carsten.android.muzzic.model.MediaKeys
import de.carsten.android.muzzic.persistence.entity.aggregation.PlaylistAggregation

@Immutable
data class PlaylistDto(
    val playlistId: String,
    val playlistName: String,
    val playlistIsAutoGenerated: Boolean,
    val playlistGenre: String?,
    val artistCount: Int,
    val albumCount: Int,
    val songCount: Int,
    val playlistDuration: Long,
    override val lastAlbumArt: String? = null,
    override val albumArts: List<String> = emptyList(),
    val collageCovers: List<CoverSource> = emptyList(),
) : AlbumArt,
    UiDto,
    Comparable<PlaylistDto> {

    override fun compareTo(other: PlaylistDto): Int {
        val c1 = this.playlistName.compareTo(other.playlistName)
        return if (c1 != 0) {
            c1
        } else {
            this.playlistDuration.compareTo(other.playlistDuration)
        }
    }

    fun toMediaItem() = MediaItem
        .Builder()
        .setMediaId("${MediaKeys.PLAYLIST_PREFIX}$playlistName")
        .setMediaMetadata(
            MediaMetadata
                .Builder()
                .setTitle(playlistName)
                .setArtworkUri(lastAlbumArt?.toUri())
                .setExtras(
                    Bundle().apply {
                        putString(MediaKeys.PLAYLIST_ID, playlistId)
                        putBoolean(MediaKeys.IS_AUTO_GENERATED, playlistIsAutoGenerated)
                        putString(MediaKeys.GENRE, playlistGenre ?: UNKNOWN)
                        putInt(MediaKeys.ARTIST_COUNT, artistCount)
                        putInt(MediaKeys.ALBUM_COUNT, albumCount)
                        putInt(MediaKeys.SONG_COUNT, songCount)
                        putLong(MediaKeys.DURATION, playlistDuration)
                    },
                )
                .setIsBrowsable(true)
                .setIsPlayable(false)
                .build(),
        ).build()

    override fun lazyKey(): String = this.playlistId
}

fun PlaylistAggregation.toDto(): PlaylistDto {
    val albumArtList = this.allAlbumArts?.split(",") ?: listOfNotNull(lastAlbumArt)
    return PlaylistDto(
        playlistId = this.playlistId,
        playlistName = this.playlistName,
        playlistIsAutoGenerated = this.playlistIsAutoGenerated,
        playlistGenre = this.playlistGenre,
        artistCount = this.artistCount,
        albumCount = this.albumCount,
        songCount = this.songCount,
        playlistDuration = this.playlistDuration,
        lastAlbumArt = this.lastAlbumArt,
        albumArts = albumArtList,
        collageCovers = albumArtList.map { CoverSource.FromPath(it) },
    )
}

fun List<PlaylistAggregation>.toDto() = map { it.toDto() }

fun MediaItem.toPlaylistDto(): PlaylistDto {
    val metadata = mediaMetadata
    val extras = metadata.extras ?: Bundle.EMPTY
    val lastArt = metadata.artworkUri?.toString()
    return PlaylistDto(
        playlistId = extras.getString(MediaKeys.PLAYLIST_ID) ?: mediaId.removePrefix(MediaKeys.PLAYLIST_PREFIX),
        playlistName = metadata.title?.toString() ?: EMPTY,
        playlistIsAutoGenerated = extras.getBoolean(MediaKeys.IS_AUTO_GENERATED),
        playlistGenre = extras.getString(MediaKeys.GENRE) ?: UNKNOWN,
        artistCount = extras.getInt(MediaKeys.ARTIST_COUNT),
        albumCount = extras.getInt(MediaKeys.ALBUM_COUNT),
        songCount = extras.getInt(MediaKeys.SONG_COUNT),
        playlistDuration = extras.getLong(MediaKeys.DURATION),
        lastAlbumArt = lastArt,
        collageCovers = listOfNotNull(lastArt).map { CoverSource.FromPath(it) },
    )
}
