package de.carsten.android.muzzic.ui.model

import androidx.compose.runtime.Immutable
import de.carsten.android.muzzic.model.AlbumArt
import de.carsten.android.muzzic.persistence.entity.aggregation.PlaylistAggregation

@Immutable
data class PlaylistDto(
    val playlistName: String,
    val playlistIsAutoGenerated: Boolean,
    val playlistGenre: String,
    val artistCount: Int,
    val albumCount: Int,
    val songCount: Int,
    val playlistDuration: Long,
    override val lastAlbumArt: String? = null,
) : AlbumArt

fun PlaylistAggregation.toDto() =
    PlaylistDto(
        playlistName = this.playlistName,
        playlistIsAutoGenerated = this.playlistIsAutoGenerated,
        playlistGenre = this.playlistGenre,
        artistCount = this.artistCount,
        albumCount = this.albumCount,
        songCount = this.songCount,
        playlistDuration = this.playlistDuration,
        lastAlbumArt = this.lastAlbumArt,
    )

fun List<PlaylistAggregation>.toDto() = map { it.toDto() }
