package de.carsten.android.muzzic.ui.model

import androidx.compose.runtime.Immutable
import androidx.media3.common.MediaItem
import de.carsten.android.muzzic.model.AlbumArt
import de.carsten.android.muzzic.model.MediaKeys
import de.carsten.android.muzzic.persistence.entity.aggregation.PlaylistAggregation

@Immutable
data class PlaylistDto(
    val playlistName: String,
    val playlistIsAutoGenerated: Boolean,
    val playlistGenre: String,
    val artistCount: Int,
    val albumCount: Int,
    val songCount: Int,
    val playlistDuration: Long,
    override val lastAlbumArt: String? = null,
) : AlbumArt

fun PlaylistAggregation.toDto() =
    PlaylistDto(
        playlistName = this.playlistName,
        playlistIsAutoGenerated = this.playlistIsAutoGenerated,
        playlistGenre = this.playlistGenre,
        artistCount = this.artistCount,
        albumCount = this.albumCount,
        songCount = this.songCount,
        playlistDuration = this.playlistDuration,
        lastAlbumArt = this.lastAlbumArt,
    )

fun List<PlaylistAggregation>.toDto() = map { it.toDto() }

fun MediaItem.toPlaylistDto(): PlaylistDto {
    val metadata = mediaMetadata
    val extras = metadata.extras ?: android.os.Bundle.EMPTY
    return PlaylistDto(
        playlistName = metadata.title?.toString() ?: "",
        playlistIsAutoGenerated = extras.getBoolean(MediaKeys.IS_AUTO_GENERATED),
        playlistGenre = extras.getString(MediaKeys.GENRE) ?: "",
        artistCount = extras.getInt(MediaKeys.ARTIST_COUNT),
        albumCount = extras.getInt(MediaKeys.ALBUM_COUNT),
        songCount = extras.getInt(MediaKeys.SONG_COUNT),
        playlistDuration = extras.getLong(MediaKeys.DURATION)
    )
}
