package de.carsten.android.muzzic.ui.screens

import android.content.res.Configuration
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import de.carsten.android.muzzic.ui.model.PlaylistDto
import de.carsten.android.muzzic.ui.navigation.MusicAppState
import de.carsten.android.muzzic.ui.screens.cards.PlaylistListItem
import de.carsten.android.muzzic.viewmodel.LibraryViewModel
import de.carsten.android.muzzic.viewmodel.PlayingQueueViewModel
import org.koin.androidx.compose.koinViewModel
import java.util.concurrent.TimeUnit

@Composable
fun PlaylistsScreen(
    modifier: Modifier = Modifier,
    appState: MusicAppState,
    libraryViewModel: LibraryViewModel = koinViewModel(),
    playingQueueViewModel: PlayingQueueViewModel,
    onPlaylistClick: (PlaylistDto) -> Unit = {},
    onPlayPlaylist: (PlaylistDto) -> Unit = {},
) {
    val playlists by libraryViewModel.playlists.collectAsStateWithLifecycle()
    PlaylistScreenContent(
        modifier = modifier,
        playlists = playlists,
        onPlaylistClick = {
            libraryViewModel.setIntoPlayingQueue(it.playlistId)
            playingQueueViewModel.setPlayQueueName(it.playlistName)
            onPlaylistClick(it)
            appState.showSnackbar("Set ${it.playlistName}")
        },
        onPlayClick = {
            libraryViewModel.playPlaylist(it.playlistId)
            playingQueueViewModel.setPlayQueueName(it.playlistName)
            onPlayPlaylist(it)
            appState.showSnackbar("Play ${it.playlistName}")
        },
        onDeleteClick = {
            libraryViewModel.deletePlaylist(it.playlistId)
        }
    )
}

@Composable
fun PlaylistScreenContent(
    modifier: Modifier,
    playlists: List<PlaylistDto>,
    onPlaylistClick: (PlaylistDto) -> Unit = {},
    onPlayClick: (PlaylistDto) -> Unit = {},
    onDeleteClick: (PlaylistDto) -> Unit = {},
) {
    Column(
        modifier =
            modifier
                .fillMaxSize()
                .background(MaterialTheme.colorScheme.background),
    ) {
        // Header
        Row(
            modifier =
                Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text(
                text = "Playlists",
                color = MaterialTheme.colorScheme.onBackground,
                fontSize = 24.sp,
                fontWeight = FontWeight.Bold,
            )

            IconButton(onClick = { /* Add playlist */ }) {
                Icon(
                    Icons.Default.Add,
                    contentDescription = "Add Playlist",
                    tint = MaterialTheme.colorScheme.onBackground,
                )
            }
        }

        LazyColumn(
            modifier =
                Modifier
                    .padding(horizontal = 16.dp)
                    .fillMaxWidth(),
            verticalArrangement = Arrangement.spacedBy(8.dp),
        ) {
            item {
                Text(
                    text = "Automatische Genre-Playlists",
                    color = MaterialTheme.colorScheme.onBackground,
                    fontSize = 16.sp,
                    fontWeight = FontWeight.SemiBold,
                    modifier = Modifier.padding(vertical = 8.dp),
                )
            }

            item {
                val autoPlaylists = remember(playlists) {
                    playlists.filter { it.playlistIsAutoGenerated }
                }
                Column {
                    autoPlaylists.forEach { playlist ->
                        PlaylistListItem(
                            playlist = playlist,
                            iconColor = MaterialTheme.colorScheme.onBackground,
                            modifier = Modifier.padding(vertical = 4.dp),
                            showGenre = playlist.playlistIsAutoGenerated,
                            onPlaylistClick = { onPlaylistClick(playlist) },
                            onPlayClick = { onPlayClick(playlist) },
                            onDeleteClick = { onDeleteClick(playlist) }
                        )
                    }
                }
            }

            item {
                Text(
                    text = "Meine Playlists",
                    color = MaterialTheme.colorScheme.onBackground,
                    fontSize = 16.sp,
                    fontWeight = FontWeight.SemiBold,
                    modifier = Modifier.padding(vertical = 8.dp),
                )
            }

            item {
                val userPlaylists = remember(playlists) {
                    playlists.filter { !it.playlistIsAutoGenerated }
                }
                Column {
                    userPlaylists.forEach { playlist ->
                        PlaylistListItem(
                            playlist = playlist,
                            iconColor = MaterialTheme.colorScheme.onBackground,
                            modifier = Modifier.padding(vertical = 4.dp),
                            onPlaylistClick = { onPlaylistClick(playlist) },
                            onPlayClick = { onPlayClick(playlist) },
                            onDeleteClick = { onDeleteClick(playlist) }
                        )
                    }
                }
            }
        }
    }
}

@Composable
@Preview
@Preview(uiMode = Configuration.UI_MODE_NIGHT_YES)
fun PlaylistsScreenPreview() {
    PlaylistScreenContent(
        Modifier.padding(2.dp),
        listOf(
            PlaylistDto("1", "Playlist 1", true, "Genre 1", 50, 500, 5000, TimeUnit.DAYS.toMillis(5)),
            PlaylistDto("2", "Playlist 2", false, "Genre 2", 50, 500, 5000, TimeUnit.DAYS.toMillis(5)),
            PlaylistDto("3", "Playlist 3", true, "Genre 3", 50, 500, 5000, TimeUnit.DAYS.toMillis(5)),
            PlaylistDto("4", "Playlist 4", false, "Genre 4", 50, 500, 5000, TimeUnit.DAYS.toMillis(5)),
            PlaylistDto("5", "Playlist 5", true, "Genre 5", 50, 500, 5000, TimeUnit.DAYS.toMillis(5)),
            PlaylistDto("6", "Playlist 6", false, "Genre 6", 50, 500, 5000, TimeUnit.DAYS.toMillis(5)),
        ),
    )
}
