package de.carsten.android.muzzic.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import de.carsten.android.muzzic.R
import de.carsten.android.muzzic.ui.FONT_SIZE_HUGE_TITLE
import de.carsten.android.muzzic.ui.FONT_SIZE_SUBTITLE
import de.carsten.android.muzzic.ui.GLASS_CONTAINER_ALPHA
import de.carsten.android.muzzic.ui.PREVIEW_DARK_MODE
import de.carsten.android.muzzic.ui.SPACING_LARGE
import de.carsten.android.muzzic.ui.SPACING_MEDIUM
import de.carsten.android.muzzic.ui.SPACING_SMALL
import de.carsten.android.muzzic.ui.SPACING_TINY
import de.carsten.android.muzzic.ui.model.ColorSource
import de.carsten.android.muzzic.ui.model.PlaylistDto
import de.carsten.android.muzzic.ui.model.composableColorSource
import de.carsten.android.muzzic.ui.navigation.MusicAppState
import de.carsten.android.muzzic.ui.screens.cards.PlaylistListItem
import de.carsten.android.muzzic.ui.theme.AppTheme
import de.carsten.android.muzzic.viewmodel.LibraryViewModel
import de.carsten.android.muzzic.viewmodel.PlayingQueueViewModel
import java.util.concurrent.TimeUnit

@Composable
fun PlaylistsScreen(
    modifier: Modifier = Modifier,
    appState: MusicAppState,
    colorSource: ColorSource = composableColorSource(),
    libraryViewModel: LibraryViewModel,
    playingQueueViewModel: PlayingQueueViewModel,
    onPlaylistClick: (PlaylistDto) -> Unit = {},
    onPlayPlaylist: (PlaylistDto) -> Unit = {},
    onDeletePlaylist: (PlaylistDto) -> Unit = {},
) {
    val uiState by libraryViewModel.uiState.collectAsStateWithLifecycle()

    PlaylistScreenContent(
        modifier = modifier,
        playlists = uiState.playlists,
        colorSource = colorSource,
        onPlaylistClick = onPlaylistClick,
        onPlayClick = onPlayPlaylist,
        onDeleteClick = onDeletePlaylist,
    )
}

@Composable
fun PlaylistScreenContent(
    modifier: Modifier,
    playlists: List<PlaylistDto>,
    colorSource: ColorSource = composableColorSource(),
    onPlaylistClick: (PlaylistDto) -> Unit = {},
    onPlayClick: (PlaylistDto) -> Unit = {},
    onDeleteClick: (PlaylistDto) -> Unit = {},
) {
    val autoPlaylists = remember(playlists) {
        playlists.filter { it.playlistIsAutoGenerated }
    }
    val userPlaylists = remember(playlists) {
        playlists.filter { !it.playlistIsAutoGenerated }
    }

    Column(
        modifier =
        modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.surface.copy(alpha = GLASS_CONTAINER_ALPHA)),
    ) {
        Row(
            modifier =
            Modifier
                .fillMaxWidth()
                .padding(SPACING_LARGE),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text(
                text = stringResource(R.string.playlists),
                color = MaterialTheme.colorScheme.onBackground,
                fontSize = FONT_SIZE_HUGE_TITLE,
                fontWeight = FontWeight.Bold,
            )

            IconButton(onClick = { /* Add playlist */ }) {
                Icon(
                    Icons.Default.Add,
                    contentDescription = stringResource(R.string.add_playlists),
                    tint = MaterialTheme.colorScheme.onBackground,
                )
            }
        }

        LazyColumn(
            modifier =
            Modifier
                .padding(horizontal = SPACING_LARGE)
                .fillMaxWidth(),
            verticalArrangement = Arrangement.spacedBy(SPACING_MEDIUM),
        ) {
            item {
                Text(
                    text = stringResource(R.string.auto_playlists),
                    color = MaterialTheme.colorScheme.onBackground,
                    fontSize = FONT_SIZE_SUBTITLE,
                    fontWeight = FontWeight.SemiBold,
                    modifier = Modifier.padding(vertical = SPACING_MEDIUM),
                )
            }

            items(
                items = autoPlaylists,
                key = { it.playlistId },
                contentType = { "Playlist" },
            ) { playlist ->
                PlaylistListItem(
                    playlist = playlist,
                    iconColor = MaterialTheme.colorScheme.onBackground,
                    colorSource = colorSource,
                    modifier = Modifier.padding(vertical = SPACING_SMALL),
                    showGenre = playlist.playlistIsAutoGenerated,
                    onPlaylistClick = { onPlaylistClick(playlist) },
                    onPlayClick = { onPlayClick(playlist) },
                    onDeleteClick = { onDeleteClick(playlist) },
                )
            }

            item {
                Text(
                    text = stringResource(R.string.my_playlists),
                    color = MaterialTheme.colorScheme.onBackground,
                    fontSize = FONT_SIZE_SUBTITLE,
                    fontWeight = FontWeight.SemiBold,
                    modifier = Modifier.padding(vertical = SPACING_MEDIUM),
                )
            }

            items(
                items = userPlaylists,
                key = { it.playlistId },
                contentType = { "Playlist" },
            ) { playlist ->
                PlaylistListItem(
                    playlist = playlist,
                    iconColor = MaterialTheme.colorScheme.onBackground,
                    colorSource = colorSource,
                    modifier = Modifier.padding(vertical = SPACING_SMALL),
                    onPlaylistClick = { onPlaylistClick(playlist) },
                    onPlayClick = { onPlayClick(playlist) },
                    onDeleteClick = { onDeleteClick(playlist) },
                )
            }
        }
    }
}

@Composable
@Preview(showBackground = true)
@Preview(uiMode = PREVIEW_DARK_MODE, showBackground = true)
fun PlaylistsScreenPreview() {
    AppTheme {
        PlaylistScreenContent(
            Modifier.padding(SPACING_TINY),
            listOf(
                PlaylistDto("1", "Playlist 1", true, "Genre 1", 50, 500, 5000, TimeUnit.DAYS.toMillis(5)),
                PlaylistDto("2", "Playlist 2", false, "Genre 2", 50, 500, 5000, TimeUnit.DAYS.toMillis(5)),
                PlaylistDto("3", "Playlist 3", true, "Genre 3", 50, 500, 5000, TimeUnit.DAYS.toMillis(5)),
                PlaylistDto("4", "Playlist 4", false, "Genre 4", 50, 500, 5000, TimeUnit.DAYS.toMillis(5)),
                PlaylistDto("5", "Playlist 5", true, "Genre 5", 50, 500, 5000, TimeUnit.DAYS.toMillis(5)),
                PlaylistDto("6", "Playlist 6", false, "Genre 6", 50, 500, 5000, TimeUnit.DAYS.toMillis(5)),
            ),
        )
    }
}
